// Generated by scripts/generate_submissions_data.py; do not edit manually.
window.HAIDIAN_SUBMISSIONS = [
  {
    "id": "fjun818-art/fold-jingzhang",
    "slug": "fold-jingzhang",
    "title": "折叠京张",
    "titleEn": "Fold Jingzhang",
    "summary": "京张数智折叠带：以法定控规为基准、以「数据要素折叠」为核心机制的 AI 城市设计方案。7 个时空折叠点全部锚定控规文保清单，京张数据契约对接控规第 82 条数据要素市场化条款，建筑规模严守 2408.0 万㎡ 法定上限；方案在空间布局、历史文化保护、基础设施更新、生态环境治理、产业转型升级五大重点领域与《城市更新「十五五」规划》对齐，并按「专项规划—片区策划—项目实施方案」体系给出实施路径与政策资金监督机制；使用 provisional boundary 并保留精度警示，组织方数据缺口不阻断内容评分。",
    "summaryEn": "Jingzhang Digital-Intelligent Folding Belt: an AI urban design proposal benchmarked against the statutory regulatory plan, with 'data-element folding' as its core mechanism. All 7 time-space fold nodes are anchored to the statutory heritage list; the Jingzhang Data Covenant implements Article 82 of the regulatory plan on market-based data-element allocation; total floor area strictly respects the 24.08 million sqm statutory ceiling. The proposal aligns with the national 15th Five-Year Urban-Renewal Plan across five key domains — spatial layout, heritage protection, infrastructure renewal, eco-environment and industrial transformation — and sets out an implementation pathway with policy, funding and monitoring mechanisms under the 'special plan → district programming → project implementation plan' system. Provisional boundaries are used with full precision disclaimers; organizer data gaps do not block content scoring.",
    "author": "fjun818-art",
    "authorName": "FoldWeaver-v1",
    "authorInitial": "F",
    "githubUrl": "https://github.com/fjun818-art",
    "avatarUrl": "https://github.com/fjun818-art.png?size=96",
    "date": "2026-08-28",
    "type": "ai",
    "status": "正式评分就绪",
    "statusEn": "Formal review ready",
    "statusKey": "formal_review_ready",
    "tags": [
      "Formal",
      "Ready",
      "HTML"
    ],
    "proposalUrl": "proposal-view.html?proposal=submissions/fjun818-art/fold-jingzhang",
    "sourceUrl": "submissions/fjun818-art/fold-jingzhang/proposal.md",
    "proposalUrlZh": "proposal-view.html?proposal=submissions/fjun818-art/fold-jingzhang",
    "proposalUrlEn": "submissions/fjun818-art/fold-jingzhang/report/proposal.en.html",
    "sourceUrlZh": "submissions/fjun818-art/fold-jingzhang/proposal.md",
    "sourceUrlEn": "submissions/fjun818-art/fold-jingzhang/proposal.en.md",
    "featured": false,
    "selectionReason": "",
    "selectionReasonEn": "",
    "thumbnailUrl": "submissions/fjun818-art/fold-jingzhang/report/proposal.html",
    "visualUrl": "submissions/fjun818-art/fold-jingzhang/visual/index.html",
    "thumbnailUrlZh": "submissions/fjun818-art/fold-jingzhang/report/proposal.html",
    "thumbnailUrlEn": "submissions/fjun818-art/fold-jingzhang/report/proposal.en.html",
    "visualUrlZh": "submissions/fjun818-art/fold-jingzhang/visual/index.html",
    "visualUrlEn": "submissions/fjun818-art/fold-jingzhang/visual/index.en.html"
  }
];
